const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const { pathToFileURL } = require("node:url");

const ROOT = path.resolve(__dirname, "..");

async function loadHarpoTrafficHelpers() {
  const sourcePath = path.join(ROOT, "harpo-traffic.js");
  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "harpo-domain-filter-"));
  const tempModulePath = path.join(tempDir, "harpo-traffic.mjs");
  fs.copyFileSync(sourcePath, tempModulePath);
  return import(pathToFileURL(tempModulePath).href);
}

test("HARPO derives quick-pick domain buckets from hostnames", async () => {
  const helpers = await loadHarpoTrafficHelpers();

  assert.equal(
    helpers.getHarpoTrafficHostname("https://api.auth.adobe.com/api/v2/requestor/configuration?device=tv"),
    "api.auth.adobe.com"
  );
  assert.equal(helpers.getHarpoTrafficHostname("*.adobe.com"), "adobe.com");
  assert.equal(helpers.getHarpoTrafficHostname("*.identity1.dishnetwork.com"), "identity1.dishnetwork.com");
  assert.equal(helpers.getHarpoTrafficHostname("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUA"), "");
  assert.equal(
    helpers.getHarpoTrafficDomainBucket("https://api.auth.adobe.com/api/v2/requestor/configuration?device=tv"),
    "adobe.com"
  );
  assert.equal(helpers.getHarpoTrafficDomainBucket("https://www.example.com/saml/login"), "example.com");
  assert.equal(helpers.getHarpoTrafficDomainBucket("https://www.bbc.co.uk/news"), "bbc.co.uk");
  assert.equal(helpers.getHarpoTrafficDomainBucket("localhost"), "localhost");
});

test("HARPO workspace renders a domain picker with HTTP status filter pills", () => {
  const html = fs.readFileSync(path.join(ROOT, "harpo.html"), "utf8");
  const js = fs.readFileSync(path.join(ROOT, "harpo.js"), "utf8");
  const appJs = fs.readFileSync(path.join(ROOT, "app.js"), "utf8");
  const restV2Learning = fs.readFileSync(path.join(ROOT, "harpo-restv2-learning.js"), "utf8");

  assert.match(html, /<title>HAR Pass Observatory<\/title>/);
  assert.match(html, /<body class="spectrum spectrum--medium spectrum--light harpo-body">/);
  assert.match(html, /<span class="harpo-wordmark">HAR Pass Observatory<\/span>/);
  assert.match(html, /<span class="harpo-subtitle[^"]*">Adobe Pass Proxyman<\/span>/);
  assert.match(html, /id="harpoFilterBar" class="harpo-filterBar harpo-omnibox" hidden/);
  assert.match(html, /class="harpo-filterControls"/);
  assert.match(html, /class="harpo-filterField harpo-filterField--domain"/);
  assert.match(html, /<label for="harpoDomainFilter" class="harpo-filterLabel/);
  assert.match(html, /<select id="harpoDomainFilter" class="harpo-filterSelect" aria-label="Domain filter">/);
  assert.match(html, /id="harpoStatusFilters" class="harpo-statusFilters" aria-label="Status filters"/);
  assert.match(html, /id="harpoStatusFilterPills" class="harpo-statusFilterPills" role="group" aria-label="HTTP status filters"/);
  assert.match(html, /class="harpo-filterActions"/);
  assert.match(html, /id="harpoJuicerBtn"/);
  assert.match(html, /harpo-actionBtn harpo-actionBtn--juicer/);
  assert.match(html, /title="Download Pass HAR"/);
  assert.match(html, />Pass</);
  assert.match(html, /title="Download Full HAR"/);
  assert.match(html, />Full</);
  assert.match(html, /class="harpo-sidebarHeader"/);
  assert.match(html, /id="harpoWorkspaceDivider"[\s\S]*class="harpo-workspaceDivider"[\s\S]*role="separator"/);
  assert.match(html, /class="harpo-downloadBtn-inner"/);
  assert.match(html, /class="harpo-downloadBtn-icon"/);
  assert.match(html, /class="spectrum-Button-label harpo-downloadBtn-label"/);
  assert.match(
    html,
    /<div id="harpoFilterBar" class="harpo-filterBar harpo-omnibox" hidden>[\s\S]*class="harpo-filterControls"[\s\S]*id="harpoStatusFilters"[\s\S]*class="harpo-filterActions"[\s\S]*id="harpoJuicerBtn"[\s\S]*id="harpoDownloadBtn"/
  );
  assert.doesNotMatch(html, /class="harpo-topbar-actions"/);
  assert.match(html, /<script src="adobe-pass-decode-helpers\.js"><\/script>/);
  assert.doesNotMatch(html, /id="harpoStats"/);
  assert.doesNotMatch(html, />PASS<\/button>/);
  assert.doesNotMatch(html, />IMS<\/button>/);
  assert.doesNotMatch(html, />MVPD<\/button>/);
  assert.doesNotMatch(html, />ERRORS<\/button>/);
  assert.doesNotMatch(html, /class="harpo-filterBtn/);

  assert.match(js, /let activeDomainFilter = "all";/);
  assert.match(js, /let activeStatusFilter = "all";/);
  assert.match(js, /DEFAULT_THEME,/);
  assert.match(js, /THEME_STORAGE_KEY,/);
  assert.match(js, /getThemeAccentMeta,/);
  assert.match(js, /normalizeThemePreference/);
  assert.match(js, /const HARPO_THEME_RAMP_STEPS = \[100,\s*200,\s*300,\s*400,\s*500,\s*600,\s*700,\s*800,\s*900,\s*1000,\s*1100,\s*1200,\s*1300,\s*1400,\s*1500,\s*1600\];/);
  assert.match(js, /let activeTheme\s+=\s+normalizeThemePreference\(DEFAULT_THEME\);/);
  assert.match(js, /function applyHarpoThemePreference\(themePreference\)/);
  assert.match(js, /body\.classList\.toggle\("spectrum--light", theme\.stop === "light"\);/);
  assert.match(js, /body\.classList\.toggle\("spectrum--dark", theme\.stop === "dark"\);/);
  assert.match(js, /body\.style\.colorScheme = theme\.stop;/);
  assert.match(js, /chrome\.storage\.local\.get\(\[THEME_STORAGE_KEY\]\)/);
  assert.match(js, /function wireHarpoThemePreferenceSync\(\)/);
  assert.match(js, /chrome\.storage\.onChanged\.addListener/);
  assert.match(js, /applyHarpoThemePreference\(payload\.theme \|\| activeTheme \|\| DEFAULT_THEME\);/);
  assert.match(js, /await hydrateHarpoThemePreference\(rawHarPayload\?\.theme \|\| DEFAULT_THEME\);/);
  assert.match(js, /wireHarpoThemePreferenceSync\(\);/);
  assert.match(appJs, /theme:\s*normalizeThemePreference\(state\.theme\),/);
  assert.match(js, /let mvpdGateOpen\s+=\s+false;/);
  assert.match(js, /let safeDomains\s+=\s+\[\];/);
  assert.match(js, /let pendingCallListAnchor = false;/);
  assert.match(js, /function renderDomainFilters\(\)/);
  assert.match(js, /function renderStatusFilters\(\)/);
  assert.match(js, /function buildStatusFilters\(\)/);
  assert.match(js, /function getDomainScopedEntries\(\)/);
  assert.match(js, /function getSelectedEntry\(\)/);
  assert.match(js, /function getSelectionAnchorEntry\(filtered = \[\]\)/);
  assert.match(js, /function anchorCallListToSelection\(listEl, filtered = \[\], selectedVisible = false\)/);
  assert.match(js, /function dedupeHarpoDomainBuckets\(domains = \[\]\)/);
  assert.match(js, /function matchesHarpoDomainList\(hostname = "", domains = \[\]\)/);
  assert.match(js, /function extractSamlMvpdDomains\(entry\)/);
  assert.match(js, /async function buildRequestContentsBody\(entry\)/);
  assert.match(js, /requestContentsMarkup \|\| `<p class="harpo-detailEmptyNote">No query string, form fields, or raw request body were recorded for this request\.<\/p>`/);
  assert.match(js, /function buildPayloadViewer\(\{/);
  assert.match(js, /function getHarpoEntryStartTimeMs\(entry = null, fallbackOrder = 0\)/);
  assert.match(js, /function formatHarpoTimestamp\(timestampMs = 0, \{ includeDate = false \} = \{\}\)/);
  assert.match(js, /let activeDetailTab\s+=\s+"analysis";/);
  assert.match(js, /function getDecodedPayloadText\(\{/);
  assert.match(js, /function extractHtmlFormPairs\(text = ""\)/);
  assert.match(js, /function extractPayloadFieldPairs\(text = "", contentType = ""\)/);
  assert.match(js, /async function decodeSamlValue\(fieldName = "", rawValue = ""\)/);
  assert.match(js, /async function buildSamlInspectorMarkup\(\{/);
  assert.match(js, /function buildHarpoPairLookup\(pairs = \[\]\)/);
  assert.match(js, /function collectHarpoAnalysisContext\(entry, responsePayload = null\)/);
  assert.match(js, /function buildAdobePassAnalysisCard\(entry, classification, harvest = null, passLearningPlan = null\)/);
  assert.match(js, /function buildPassVerdict\(pass, classification\)/);
  assert.match(js, /function buildPassUsageSummary\(entry, classification, harvest = null\)/);
  assert.match(js, /function buildPassObservedUsageRows\(entry, classification, harvest = null\)/);
  assert.match(js, /function buildPassIdentityRows\(entry, classification, harvest = null\)/);
  assert.match(js, /function buildPassDocumentationSummary\(pass\)/);
  assert.match(js, /function buildPassLiveActionItems\(entry, classification, harvest = null\)/);
  assert.match(js, /function buildHarpoRestV2LearningPlan\(entry, classification, harvest = null\)/);
  assert.match(js, /function buildHarpoDcrLearningPlan\(entry, classification, harvest = null\)/);
  assert.match(js, /function buildHarpoPassLearningPlan\(entry, classification, harvest = null\)/);
  assert.match(js, /function buildHarpoLearningStatusMessage\(plan = null, stage = "ready", unresolved = \[\]\)/);
  assert.match(js, /function buildLegacySamlAssertionConsumerHeaderNotes\(entry, formValues = \{\}\)/);
  assert.match(js, /function buildSupportStatusListLead\(pass\)/);
  assert.match(js, /Implementation identification/);
  assert.match(js, /Observed usage/);
  assert.match(js, /Official documentation/);
  assert.match(js, /Live action helper/);
  assert.match(js, /Live runtime evidence/);
  assert.match(js, /RequestorId/);
  assert.match(js, /Registration code/);
  assert.match(js, /Selected MVPD/);
  assert.match(js, /Observed client platform/);
  assert.match(js, /Callback deviceId/);
  assert.match(js, /Callback deviceInfo/);
  assert.match(js, /Adobe Pass SAML system call detected\./);
  assert.match(js, /Adobe Pass system traffic cop for browser handoff to the selected TV Provider/);
  assert.match(js, /Location header shows Adobe Pass handing the browser to the selected TV Provider or partner identity page/);
  assert.match(js, /SAMLResponse is present, which means Adobe Pass is consuming the returning MVPD assertion/);
  assert.match(js, /This is an Adobe Pass system call\./);
  assert.match(js, /pass\.migration\.observations/);
  assert.match(js, /LEARN THIS REST V2 CALL/);
  assert.match(js, /LEARN THIS DCR CALL/);
  assert.match(js, /data-harpo-pass-learning=/);
  assert.match(js, /data-harpo-pass-learning-status/);
  assert.match(js, /data-harpo-restv2-learning=/);
  assert.match(js, /data-harpo-dcr-learning=/);
  assert.match(js, /data-harpo-restv2-learning-status/);
  assert.match(js, /openHarpoDcrInteractiveDocsPlan\(passLearningPlan\)/);
  assert.match(js, /openHarpoRestV2InteractiveDocsPlan\(passLearningPlan\)/);
  assert.match(js, /inferHarpoClientPlatform/);
  assert.match(js, /sizeLabel = "bytes"/);
  assert.match(js, /responseBodyText \? "bytes" : "wire bytes"/);
  assert.match(js, /Chrome reported \$\{responseBodySize\} wire bytes, but no readable response body was recorded\./);
  assert.match(js, /Request Payload/);
  assert.match(js, /Response Body/);
  assert.match(js, /buildHarpoCodeGenerationMarkup\(entry\)/);
  assert.match(js, /function escapeHarpoShellArgument\(value = "", \{ singleLine = false \} = \{\}\)/);
  assert.match(js, /buildHarpoCurlSnippet\(entry\)/);
  assert.match(js, /buildHarpoFetchSnippet\(entry\)/);
  assert.match(js, /return parts\.join\(" "\);/);
  assert.match(js, /data-harpo-copy-target="curl"/);
  assert.match(js, /data-harpo-copy-target="fetch"/);
  assert.match(js, /data-harpo-code-sample="curl"/);
  assert.match(js, /data-harpo-code-sample="fetch"/);
  assert.match(js, /Click title to copy/);
  assert.match(js, /async function copyHarpoText\(text = ""\)/);
  assert.match(js, /navigator\.clipboard\.writeText\(value\)/);
  assert.match(js, /function wireHarpoCodeCopy\(detailEl\)/);
  assert.match(js, /window\.alert\("HARPO could not copy this code sample to the clipboard\."\)/);
  assert.match(js, /wireHarpoCodeCopy\(detailEl\);/);
  assert.match(js, /role="tablist" aria-label="Request details"/);
  assert.match(js, /data-harpo-detail-tab="analysis"/);
  assert.match(js, /data-harpo-detail-tab="headers"/);
  assert.match(js, /data-harpo-detail-tab="code"/);
  assert.match(js, /function wireWorkspaceDivider\(\)/);
  assert.match(js, /class="harpo-detailCard-count"/);
  assert.match(js, /function buildHarExportFilename\(kind = "full"\)/);
  assert.match(js, /const uploadedFileName = String\(rawHarPayload\?\.fileName \|\| ""\)\.trim\(\);/);
  assert.match(js, /if \(kind === "juiced" && uploadedBaseName\) \{/);
  assert.match(js, /return `\$\{uploadedBaseName\}-juiced-\$\{ts\}\.har`;/);
  assert.match(js, /function downloadHarObject\(harObject = null, kind = "full"\)/);
  assert.match(js, /function buildHarpoJuicerKeepDomains\(\)/);
  assert.match(js, /function collectHarpoJuicerEvidenceDomains\(record = null\)/);
  assert.match(js, /function shouldIncludeInJuicedHarEntry\(record = null, keepDomains = \[\]\)/);
  assert.match(js, /const evidenceDomains = collectHarpoJuicerEvidenceDomains\(record\);/);
  assert.match(js, /isHarpoAdobeTraffic\(hostname\) \|\| matchesHarpoDomainList\(hostname, keepDomains\)/);
  assert.match(js, /function buildJuicedHar\(\)/);
  assert.match(js, /Generated by HARPO JUICER\./);
  assert.match(js, /Adobe ecosystem support/);
  assert.match(js, /detected MVPD auth traffic/);
  assert.match(js, /function wireHarExportButtons\(\)/);
  assert.match(js, /downloadHarObject\(nextJuicedHar, "juiced"\)/);
  assert.match(js, /window\.localStorage\.setItem\(HARPO_SIDEBAR_WIDTH_STORAGE_KEY/);
  assert.match(js, /\.sort\(\(a, b\) => a\.startedMs - b\.startedMs \|\| a\.originalIndex - b\.originalIndex\)/);
  assert.match(js, /chronological · \$\{formatHarpoTimestamp\(firstEntry\.startedMs, \{ includeDate: true \}\)\} → \$\{formatHarpoTimestamp\(lastEntry\.startedMs\)\}/);
  assert.match(js, /formatHarpoSequence\(sequence\)/);
  assert.match(js, /Adobe Pass Analysis/);
  assert.match(js, /SAML Inspector/);
  assert.match(js, /Original Value/);
  assert.match(js, /Supporting Fields/);
  assert.match(js, /Decoded XML/);
  assert.match(js, /SUPPORTED/);
  assert.match(js, /UNSUPPORTED LEGACY V1/);
  assert.match(js, /NOT IN 2026 API SPEC/);
  assert.match(js, /pass\?\.support\?\.status === "current"/);
  assert.match(js, /REST V2 migration/);
  assert.match(js, /content\?\.comment/);
  assert.match(js, /const domainBucket = getHarpoTrafficDomainBucket\(hostname\);/);
  assert.match(js, /const sharedDecodeHelpers = globalThis\.AdobePassDecodeHelpers \|\| \{\};/);
  assert.match(js, /let mvpdDomains\s+=\s+dedupeHarpoDomainBuckets\(rawHarPayload\?\.mvpdDomains \|\| \[\]\);/);
  assert.match(js, /const samlMvpdDomains = extractSamlMvpdDomains\(entry\);/);
  assert.match(js, /isHarpoPassSamlAssertionConsumer\(url\)/);
  assert.match(js, /samlMvpdDomains\.length > 0/);
  assert.match(js, /mvpdGateOpen = true;/);
  assert.match(js, /mvpdDomains = dedupeHarpoDomainBuckets\(\[\.\.\.mvpdDomains, \.\.\.samlMvpdDomains\]\);/);
  assert.match(js, /matchesHarpoDomainList\(hostname, mvpdDomains\)/);
  assert.match(js, /programmerDomains:\s*safeDomains,/);
  assert.match(js, /classifiedEntries\.forEach/);
  assert.match(js, /return classifiedEntries\.filter\(\(entry\) => activeDomainFilter === "all" \|\| entry\.domainBucket === activeDomainFilter\);/);
  assert.match(js, /if \(activeStatusFilter !== "all" && String\(status\) !== activeStatusFilter\) return false;/);
  assert.match(js, /const selectedEntry = getSelectedEntry\(\);/);
  assert.match(js, /pendingCallListAnchor = true;/);
  assert.match(js, /anchorEl\.scrollIntoView\(\{ block: selectedVisible \? "nearest" : "center" \}\);/);
  assert.match(js, /if \(selectedIndex === -1\) \{\s*renderEmptyDetail\("Select a call"/s);
  assert.match(js, /inflateBytes\(bytes, "deflate-raw"\)/);
  assert.match(js, /inflateBytes\(bytes, "deflate"\)/);
  assert.match(js, /sourceLabel:\s*"request query string"/);
  assert.match(js, /"response HTML form"/);
  assert.match(js, /void renderDetail\(c\);/);
  assert.match(js, /async function renderDetail\(\{ entry, classification, hostname, startedMs = 0, sequence = 0 \}\)/);
  assert.match(js, /const analysisContext = collectHarpoAnalysisContext\(entry, responsePayload\);/);
  assert.match(js, /const passLearningPlan = buildHarpoPassLearningPlan\(entry, classification, analysisContext\);/);
  assert.match(js, /const codeGenerationMarkup = buildHarpoCodeGenerationMarkup\(entry\);/);
  assert.match(js, /detailRenderToken\s*\+=\s*1;/);
  assert.match(js, /responsePayload\.samlMarkup \|\| ""/);
  assert.match(js, /No query string, form fields, or raw request body were recorded for this request\./);
  assert.match(js, /JWT Inspector/);
  assert.match(js, /Base64 Inspector/);
  assert.match(js, /buildJwtInspectorMarkup\(\{/);
  assert.match(js, /buildBase64InspectorMarkup\(\{/);
  assert.match(js, /select\.addEventListener\("change", \(\) => \{/);
  assert.match(js, /renderStatusFilters\(\);/);
  assert.match(js, /function getHarpoCallListGroup\(record = null\)/);
  assert.match(js, /groupHeader\.className = "harpo-callGroupHeader"/);
  assert.match(js, /data-status-filter="\$\{escHtml\(filter\.key\)\}"/);
  assert.doesNotMatch(js, /harpo-filterPill-count/);
  assert.doesNotMatch(js, /function renderStats\(\)/);
  assert.doesNotMatch(js, /let activeFilter\s+=\s+"all";/);
  assert.doesNotMatch(js, /let programmerDomains\s+=\s+\[\];/);
  assert.doesNotMatch(js, /let showAllTraffic\s+=\s+true;/);
  assert.doesNotMatch(js, /function renderTrafficScopeToggle\(\)/);
  assert.doesNotMatch(js, /function getScopeFilteredEntries\(\)/);
  assert.doesNotMatch(js, /function renderPhaseNav\(\)/);
  assert.doesNotMatch(js, /The selected call is still open in the detail panel, but it is hidden by the current filters\./);
  assert.doesNotMatch(js, /The selected call is hidden by the current filters\. Clear or widen the filters to bring it back into the list\./);
  assert.doesNotMatch(js, /const visibleSelection = filtered\.some\(\(entry\) => entry\.idx === selectedIndex\);\s*if \(!visibleSelection\) \{\s*selectedIndex = -1;/s);
  assert.match(restV2Learning, /const HARPO_REST_V2_INTERACTIVE_BASE_URL = "https:\/\/developer\.adobe\.com\/adobe-pass\/api\/rest_api_v2\/interactive\/";/);
  assert.match(restV2Learning, /const HARPO_DCR_INTERACTIVE_BASE_URL = "https:\/\/developer\.adobe\.com\/adobe-pass\/api\/dcr-api\/interactive\/";/);
  assert.match(restV2Learning, /endpointId: "dcr-client-register"/);
  assert.match(restV2Learning, /operationId: "processSoftwareStatementUsingPOST"/);
  assert.match(restV2Learning, /endpointId: "dcr-client-token"/);
  assert.match(restV2Learning, /operationId: "generateAccessTokenUsingPOST"/);
  assert.match(restV2Learning, /endpointId: "rest-v2-sessions-create"/);
  assert.match(restV2Learning, /operationId: "createSessionUsingPOST"/);
  assert.match(restV2Learning, /export function getHarpoDcrInteractiveDocsEntryFromEndpointId\(endpointId = ""\)/);
  assert.match(restV2Learning, /export function buildHarpoDcrInteractiveDocsUrl\(anchor = ""\)/);
  assert.match(restV2Learning, /export async function openHarpoRestV2InteractiveDocsPlan\(plan = null\)/);
  assert.match(restV2Learning, /export async function openHarpoDcrInteractiveDocsPlan\(plan = null\)/);
  assert.match(restV2Learning, /export async function hydrateHarpoRestV2InteractiveDocsTab\(tabId, plan = null\)/);
  assert.match(restV2Learning, /export async function hydrateHarpoDcrInteractiveDocsTab\(tabId, plan = null\)/);
});

test("HARPO call list uses inspector-style row dividers and persistent status emphasis", () => {
  const css = fs.readFileSync(path.join(ROOT, "harpo.css"), "utf8");

  assert.match(css, /\.harpo-filterField,\s*\.harpo-statusFilters\s*\{[\s\S]*flex-direction:\s*column;[\s\S]*padding:\s*0;/s);
  assert.match(css, /\.harpo-filterBar\s*\{[\s\S]*justify-content:\s*space-between;/s);
  assert.match(css, /\.harpo-omnibox\s*\{[\s\S]*box-shadow:/s);
  assert.match(css, /\.harpo-filterControls\s*\{[\s\S]*flex-wrap:\s*wrap;/s);
  assert.match(css, /\.harpo-filterActions\s*\{[\s\S]*gap:\s*var\(--spectrum-spacing-150\);[\s\S]*margin-inline-start:\s*auto;/s);
  assert.match(css, /\.harpo-filterPicker\s*\{[\s\S]*display:\s*flex;[\s\S]*inline-size:\s*min\(100%,\s*clamp\(11rem,\s*17vw,\s*14rem\)\);[\s\S]*max-inline-size:\s*100%;/s);
  assert.match(css, /\.harpo-filterSelect\s*\{[\s\S]*inline-size:\s*100%;[\s\S]*min-inline-size:\s*0;[\s\S]*min-height:\s*38px;/s);
  assert.doesNotMatch(css, /\.harpo-filterPicker\s*\{[^}]*width:\s*min\(340px,\s*100%\);/s);
  assert.doesNotMatch(css, /\.harpo-filterSelect\s*\{[^}]*width:\s*100%;/s);
  assert.match(css, /\.harpo-statusFilterPills\s*\{/);
  assert.match(css, /\.harpo-downloadBtn-inner\s*\{/);
  assert.match(css, /\.harpo-downloadBtn-icon\s*\{/);
  assert.match(css, /\.harpo-actionBtn\s*\{/);
  assert.match(css, /\.harpo-actionBtn--juicer\s*\{/);
  assert.match(css, /\.harpo-downloadBtn-icon--juicer\s*\{/);
  assert.match(css, /\.harpo-filterPill\s*\{/);
  assert.match(css, /\.harpo-filterPill--active\s*\{/);
  assert.doesNotMatch(css, /\.harpo-filterPill-count\s*\{/);
  assert.doesNotMatch(css, /\.harpo-topbar-actions\s*\{/);
  assert.doesNotMatch(css, /\.harpo-trafficScope\s*\{/);
  assert.doesNotMatch(css, /\.harpo-trafficScopeCheckbox\s*\{/);
  assert.match(css, /body\.harpo-body\.spectrum--light\s*\{/);
  assert.match(css, /body\.harpo-body\.spectrum--dark\s*\{/);
  assert.match(css, /--harpo-topbar-bg:/);
  assert.match(css, /--harpo-workspace-bg:/);
  assert.match(css, /--harpo-detail-bg:/);
  assert.match(css, /--harpo-card-bg:/);
  assert.match(css, /--harpo-action-btn-bg:/);
  assert.match(css, /--harpo-scrollbar-track:/);
  assert.match(css, /body\.harpo-body::before\s*\{/);
  assert.match(css, /\.harpo-topbar\s*\{[\s\S]*background:\s*var\(--harpo-topbar-bg\);[\s\S]*margin:\s*0;[\s\S]*border-radius:\s*0;[\s\S]*box-shadow:\s*none;/s);
  assert.match(css, /\.harpo-workspace\s*\{[\s\S]*--harpo-sidebar-scrollbar-safe-zone:\s*32px;[\s\S]*--harpo-sidebar-status-text-pad:\s*16px;[\s\S]*background:\s*var\(--harpo-workspace-bg\);/s);
  assert.match(css, /\.harpo-workspace\s*\{[\s\S]*margin:\s*0;[\s\S]*border-radius:\s*0;[\s\S]*box-shadow:\s*none;/s);
  assert.match(css, /\.harpo-sidebarHeader\s*\{[\s\S]*padding:\s*0 var\(--spectrum-spacing-250\);/s);
  assert.match(css, /\.harpo-sidebarHeaderStatus\s*\{[\s\S]*text-align:\s*right;[\s\S]*padding-inline-end:\s*var\(--harpo-sidebar-status-text-pad\);/s);
  assert.match(css, /\.harpo-callList\s*\{[\s\S]*gap:\s*0;[\s\S]*padding:\s*0;[\s\S]*scrollbar-gutter:\s*stable;[\s\S]*background:\s*transparent;/s);
  assert.match(css, /\.harpo-callList::\-webkit-scrollbar\s*\{/);
  assert.match(css, /\.harpo-callList::\-webkit-scrollbar-thumb\s*\{/);
  assert.match(css, /\.harpo-callGroupHeader\s*\{/);
  assert.match(css, /\.harpo-callGroupLabel\s*\{/);
  assert.match(css, /\.harpo-callGroupHeader\s*\{[\s\S]*padding:\s*0 var\(--spectrum-spacing-250\);/s);
  assert.match(css, /\.harpo-callItem\s*\{[\s\S]*padding:\s*13px var\(--spectrum-spacing-225\) 13px var\(--spectrum-spacing-250\);[\s\S]*border-bottom:\s*1px solid rgba\(255,\s*255,\s*255,\s*0\.055\);[\s\S]*border-left:\s*2px solid transparent;[\s\S]*border-radius:\s*0;/s);
  assert.match(css, /\.harpo-callMeta\s*\{[\s\S]*min-width:\s*64px;[\s\S]*padding-inline-end:\s*var\(--harpo-sidebar-status-text-pad\);/s);
  assert.match(css, /\.harpo-callStatus\s*\{[\s\S]*padding-inline-end:\s*var\(--harpo-sidebar-status-text-pad\);[\s\S]*border-radius:\s*0;/s);
  assert.doesNotMatch(css, /\.harpo-callItem:nth-child\(even\)\s*\{/);
  assert.match(css, /\.harpo-callItem--error\s*\{/);
  assert.match(css, /\.harpo-callItem--selected\s*\{[\s\S]*border-left-color:\s*var\(--harpo-shell-accent\);/s);
  assert.match(css, /\.harpo-callItem--selected:hover\s*\{/);
  assert.match(css, /--harpo-callItem-bg:\s*var\(--harpo-row-error-bg\)/);
  assert.match(css, /border-left-color:\s*var\(--harpo-shell-negative\)/);
  assert.match(css, /\.harpo-callItem--error:hover,\s*\.harpo-callItem--selected\.harpo-callItem--error\s*\{/s);
  assert.match(css, /--harpo-callItem-bg:\s*var\(--harpo-row-error-bg-hover\)/);
  assert.match(css, /\.harpo-detailCard-count\s*\{/);
  assert.match(css, /\.harpo-detailCard-header--copy\s*\{/);
  assert.match(css, /\.harpo-detailCard-header--copy:hover\s*\{/);
  assert.match(css, /\.harpo-detailCard-header--copy:focus-visible\s*\{/);
  assert.match(css, /\.harpo-detailCard-copyStatus\s*\{/);
  assert.match(css, /\.harpo-detailCard-copyStatus\[data-state="success"\]\s*\{/);
  assert.match(css, /\.harpo-detailCard-copyStatus\[data-state="error"\]\s*\{/);
  assert.match(css, /\.harpo-analysisBadgeRow\s*\{/);
  assert.match(css, /\.harpo-migrationBox\s*\{/);
  assert.match(css, /\.harpo-docLink\s*\{/);
  assert.match(css, /\.harpo-docLink--action\s*\{/);
  assert.match(css, /\.harpo-learningStatus\s*\{/);
  assert.match(css, /\.harpo-learningStatus\[data-tone="success"\]\s*\{/);
  assert.match(css, /\.harpo-inlineLink\s*\{/);
  assert.match(css, /\.harpo-detailSubsection\s*\+\s*\.harpo-detailSubsection\s*\{/);
  assert.match(css, /\.harpo-detailTabs\s*\{[\s\S]*position:\s*sticky;[\s\S]*gap:\s*var\(--spectrum-spacing-300\);[\s\S]*padding:\s*0 28px;[\s\S]*background:\s*var\(--harpo-tabs-bg\);/s);
  assert.match(css, /\.harpo-detailTab\s*\{[\s\S]*display:\s*inline-flex;[\s\S]*flex:\s*0 0 auto;[\s\S]*padding:\s*16px 12px 14px;/s);
  assert.match(css, /\.harpo-payloadMeta\s*\{/);
  assert.match(css, /\.harpo-bodyViewer--xml\s*\{/);
  assert.match(css, /\.harpo-samlMessages\s*\{/);
  assert.match(css, /\.harpo-samlMessage\s*\{/);
  assert.match(css, /\.harpo-samlDecodeMethod\s*\{/);
  assert.match(css, /\.harpo-samlLabel\s*\{/);
  assert.match(css, /\.harpo-phase--Pass\s*\{/);
  assert.match(css, /\.harpo-omnibox\s*\{/);
  assert.match(css, /\.harpo-filterField,\s*\n\.harpo-statusFilters\s*\{/);
  assert.match(css, /flex-direction:\s*column;/);
  assert.match(css, /\.harpo-filterActions \.spectrum-Button\s*\{/);
  assert.match(css, /\.harpo-filterActions \.spectrum-Button:disabled\s*\{/);
});

test("HARPO ships the shared Adobe Pass decoder helper for JWT, Base64, and SAML", () => {
  const helperSource = fs.readFileSync(path.join(ROOT, "adobe-pass-decode-helpers.js"), "utf8");

  assert.match(helperSource, /AdobePassDecodeHelpers/);
  assert.match(helperSource, /function decodeJwtToken\(token = ""\)/);
  assert.match(helperSource, /function extractDirectJwtCarrierFromText\(rawText = ""\)/);
  assert.match(helperSource, /function inspectBase64Value\(rawInput = ""\)/);
  assert.match(helperSource, /function looksLikeBase64Value\(text = ""\)/);
  assert.match(helperSource, /function extractDirectBase64CarrierFromText\(rawText = ""\)/);
  assert.match(helperSource, /extractBase64CandidateFromText\(normalizedInput\) \|\| \(looksLikeBase64Value\(normalizedInput\) \? normalizedInput : ""\)/);
  assert.match(helperSource, /uniqueStringArray\(\[candidate, tryDecodeURIComponentValue\(candidate\)\]\)\.filter\(looksLikeBase64Value\)/);
  assert.match(helperSource, /const rawTextSource = extractDirectBase64CarrierFromText\(rawText\);/);
  assert.match(helperSource, /originValue:\s*rawTextSource/);
  assert.doesNotMatch(helperSource, /const embeddedMatches = normalized\.match/);
  assert.match(helperSource, /async function decodeSamlValue\(fieldName = "", rawValue = ""\)/);
  assert.match(helperSource, /async function extractSamlMatches\(\{/);
  assert.match(helperSource, /function extractJwtMatches\(\{/);
  assert.match(helperSource, /const rawTextSource = extractDirectJwtCarrierFromText\(rawText\);/);
  assert.match(helperSource, /originValue:\s*rawTextSource/);
  assert.doesNotMatch(helperSource, /const rawMatch = candidate\.match/);
  assert.match(helperSource, /function extractBase64Matches\(\{/);
  assert.match(helperSource, /module\.exports = helpers/);
});

test("HARPO recognizes SAML assertion consumer as the Adobe Pass browser handoff system call", () => {
  const trafficSource = fs.readFileSync(path.join(ROOT, "harpo-traffic.js"), "utf8");
  const harpoSource = fs.readFileSync(path.join(ROOT, "harpo.js"), "utf8");

  assert.match(trafficSource, /id: "system-sp-saml-assertion-consumer"/);
  assert.match(trafficSource, /Adobe Pass browser-SAML system endpoint on the sp\.auth host\./);
  assert.match(trafficSource, /Broker the browser between Adobe Pass and the selected TV Provider \(MVPD\), then consume the returning SAML assertion/);
  assert.match(trafficSource, /This endpoint is the Adobe Pass system traffic cop for browser SAML handoff/);
  assert.match(trafficSource, /Use the live Location, Referer, Origin, Cookie, and SAML form fields to determine which leg of the handoff the customer is currently on\./);
  assert.match(trafficSource, /status: "system"/);
  assert.match(harpoSource, /Adobe Pass system call \(browser SSO \/ SAML plumbing\)/);
  assert.match(harpoSource, /ADOBE PASS SYSTEM CALL/);
  assert.match(harpoSource, /System handoff leg/);
  assert.match(harpoSource, /Request Referer/);
  assert.match(harpoSource, /Response Location/);
});

test("HARPO recorder preserves response body encoding metadata for later inspection", () => {
  const backgroundSource = fs.readFileSync(path.join(ROOT, "background.js"), "utf8");
  const harpoSource = fs.readFileSync(path.join(ROOT, "harpo.js"), "utf8");

  assert.match(backgroundSource, /encoding:\s*result\.base64Encoded \? "base64" : ""/);
  assert.match(backgroundSource, /content:\s*\{[\s\S]*encoding[\s\S]*comment/s);
  assert.match(backgroundSource, /const HARPO_BODY_FETCH_RETRY_DELAYS_MS = \[120, 260, 520\]/);
  assert.match(backgroundSource, /const HARPO_NETWORK_MAX_TOTAL_BUFFER_SIZE = 100 \* 1024 \* 1024/);
  assert.match(backgroundSource, /const HARPO_NETWORK_MAX_RESOURCE_BUFFER_SIZE = 10 \* 1024 \* 1024/);
  assert.match(backgroundSource, /const HARPO_NETWORK_MAX_POST_DATA_SIZE = 1024 \* 1024/);
  assert.match(backgroundSource, /const HARPO_FETCH_INTERCEPT_RESOURCE_TYPES = \["Document", "XHR", "Fetch", "Script", "Other"\]/);
  assert.match(backgroundSource, /function harpoShouldRetryBodyFetch\(errorMessage = ""\)/);
  assert.match(backgroundSource, /function harpoBuildEmptyBodyResult\(comment = ""\)/);
  assert.match(backgroundSource, /function harpoHasBodyResult\(bodyResult = null\)/);
  assert.match(backgroundSource, /function harpoFormatByteCount\(bytes = 0\)/);
  assert.match(backgroundSource, /function harpoBuildMissingBodyComment\(/);
  assert.match(backgroundSource, /function harpoRememberCapturedBodyResult\(requestKey = "", bodyResult = null, fallbackComment = ""\)/);
  assert.match(backgroundSource, /function harpoShouldTreatResponseAsBodyless\(request = null, response = null\)/);
  assert.match(backgroundSource, /requestContentType/);
  assert.match(backgroundSource, /bodyPromise/);
  assert.match(backgroundSource, /params\.redirectResponse/);
  assert.match(backgroundSource, /harpoNormalizeResponseRecord/);
  assert.match(backgroundSource, /function harpoMergeHeaders\(existingHeaders = \[\], nextHeaders = \[\]\)/);
  assert.match(backgroundSource, /function harpoMergeResponseRecord\(existingResponse = null, nextResponse = null\)/);
  assert.match(backgroundSource, /function harpoMatchesDomainList\(url, domains = \[\]\)/);
  assert.match(backgroundSource, /isHarpoPhysicalAssetTraffic/);
  assert.match(backgroundSource, /function harpoShouldPersistEntry\(entry, captureSession = createHarpoCaptureSession\(\)\)/);
  assert.match(backgroundSource, /rootTabId:\s+null,/);
  assert.match(backgroundSource, /tabIds:\s+new Set\(\),/);
  assert.match(backgroundSource, /capturedResponseBodies:\s+new Map\(\),/);
  assert.match(backgroundSource, /pendingCapturedResponseBodies:\s+new Map\(\),/);
  assert.match(backgroundSource, /fetchResponseBodies:\s+new Map\(\),/);
  assert.match(backgroundSource, /pendingFetchResponseBodies:\s+new Map\(\),/);
  assert.match(backgroundSource, /pendingStreamBodies:\s+new Map\(\),/);
  assert.match(backgroundSource, /pendingRequestExtras:\s+new Map\(\),/);
  assert.match(backgroundSource, /observedRequests:\s+new Map\(\),/);
  assert.match(backgroundSource, /pendingRequestPostData:\s+new Map\(\),/);
  assert.match(backgroundSource, /completedObservedRequests:\s+new Map\(\),/);
  assert.match(backgroundSource, /function harpoBuildRequestKey\(tabId, requestId\)/);
  assert.match(backgroundSource, /function harpoBase64ToBytes\(base64 = ""\)/);
  assert.match(backgroundSource, /function harpoBytesToBase64\(bytes = new Uint8Array\(0\)\)/);
  assert.match(backgroundSource, /function harpoTextToBytes\(text = ""\)/);
  assert.match(backgroundSource, /function harpoBytesToUtf8Text\(bytes = new Uint8Array\(0\)\)/);
  assert.match(backgroundSource, /function harpoDecodeBase64Utf8\(base64 = ""\)/);
  assert.match(backgroundSource, /function harpoConcatByteChunks\(chunks = \[\]\)/);
  assert.match(backgroundSource, /function harpoCombineBase64Chunks\(chunks = \[\]\)/);
  assert.match(backgroundSource, /function harpoNormalizeContentType\(contentType = ""\)/);
  assert.match(backgroundSource, /function harpoIsTextualContentType\(contentType = ""\)/);
  assert.match(backgroundSource, /function harpoBuildStreamBodyResult\(requestKey = ""\)/);
  assert.match(backgroundSource, /function harpoResolveResponseContentType\(response = null\)/);
  assert.match(backgroundSource, /function harpoNormalizeCapturedBodyResult\(bodyResult = null, \{ contentType = "" \} = \{\}\)/);
  assert.match(backgroundSource, /function harpoNormalizeFetchHeaderEntries\(headers = \[\]\)/);
  assert.match(backgroundSource, /function harpoIsFetchRedirectResponse\(params = \{\}\)/);
  assert.match(backgroundSource, /function harpoBuildFetchBodyResult\(result = null, contentType = ""\)/);
  assert.match(backgroundSource, /function harpoResolveRequestContentType\(request = null\)/);
  assert.match(backgroundSource, /function harpoBuildRequestBodyResult\(result = null, contentType = ""\)/);
  assert.match(backgroundSource, /encoding:\s*""/);
  assert.match(backgroundSource, /!harpoIsTextualContentType\(contentType\)/);
  assert.match(backgroundSource, /function harpoSendDebuggerCommand\(debuggee, method, commandParams = \{\}\)/);
  assert.match(backgroundSource, /function harpoMaybeCaptureRequestPostData\(tabId, requestId = "", requestKey = "", requestRecord = null, requestMeta = \{\}\)/);
  assert.match(backgroundSource, /function harpoContinueFetchRequest\(debuggeeId, requestId = ""\)/);
  assert.match(backgroundSource, /async function harpoReadIoStreamAsBase64\(debuggeeId, streamHandle = ""\)/);
  assert.match(backgroundSource, /async function harpoFulfillFetchResponse\(debuggeeId, requestId = "", params = \{\}, body = null\)/);
  assert.match(backgroundSource, /async function harpoHandleFetchRequestPaused\(debuggeeId, params = \{\}\)/);
  assert.match(backgroundSource, /function harpoBuildObservedBodyPromise\(request = null, debuggeeId = 0, requestId = "", requestKey = ""\)/);
  assert.match(backgroundSource, /function harpoCaptureObservedBody\(/);
  assert.match(backgroundSource, /const responseContentType = harpoResolveResponseContentType\(response\)/);
  assert.match(backgroundSource, /function harpoMaybeStartStreamingBody\(tabId, requestKey = "", requestId = "", resourceType = ""\)/);
  assert.match(backgroundSource, /function harpoFinalizeCapturedRequest\(requestKey,/);
  assert.match(backgroundSource, /function harpoPromoteObservedRequest\(requestKey\)/);
  assert.match(backgroundSource, /function harpoPromoteObservedRequests\(\)/);
  assert.match(backgroundSource, /function harpoAttachDebuggerToTab\(tabId\)/);
  assert.match(backgroundSource, /"Network\.enable", \{\s*maxTotalBufferSize:\s*HARPO_NETWORK_MAX_TOTAL_BUFFER_SIZE,[\s\S]*maxResourceBufferSize:\s*HARPO_NETWORK_MAX_RESOURCE_BUFFER_SIZE,[\s\S]*maxPostDataSize:\s*HARPO_NETWORK_MAX_POST_DATA_SIZE/s);
  assert.match(backgroundSource, /"Network\.configureDurableMessages", \{\s*enable:\s*true,[\s\S]*maxTotalBufferSize:\s*HARPO_NETWORK_MAX_TOTAL_BUFFER_SIZE/s);
  assert.match(backgroundSource, /"Fetch\.enable", \{\s*patterns:\s*HARPO_FETCH_INTERCEPT_RESOURCE_TYPES\.map/);
  assert.match(backgroundSource, /"Fetch\.disable"/);
  assert.match(backgroundSource, /"Fetch\.takeResponseBodyAsStream"/);
  assert.match(backgroundSource, /"Fetch\.fulfillRequest"/);
  assert.match(backgroundSource, /"IO\.read"/);
  assert.match(backgroundSource, /"IO\.close"/);
  assert.match(backgroundSource, /"Network\.getRequestPostData", \{\s*requestId:\s*normalizedRequestId\s*\}/);
  assert.match(backgroundSource, /"Network\.streamResourceContent", \{ requestId \}/);
  assert.match(backgroundSource, /function harpoHandleTrackedTabCreated\(tab\)/);
  assert.match(backgroundSource, /function harpoHandleCreatedNavigationTarget\(details\)/);
  assert.match(backgroundSource, /captureSession:\s+createHarpoCaptureSession\(\)/);
  assert.match(backgroundSource, /programmerDomains:\s+\[\],/);
  assert.match(backgroundSource, /if \(params\.redirectResponse\) \{\s*harpoState\.captureSession = updateHarpoCaptureSessionFromResponse\(/s);
  assert.match(backgroundSource, /harpoState\.captureSession = updateHarpoCaptureSessionFromRequest\(/);
  assert.match(backgroundSource, /const captureDecision = evaluateHarpoCaptureSession\(harpoState\.captureSession, url,\s*\{/);
  assert.match(backgroundSource, /case "Network\.requestWillBeSentExtraInfo": \{/);
  assert.match(backgroundSource, /const observedRequest = harpoState\.observedRequests\.get\(requestKey\)/);
  assert.match(backgroundSource, /harpoPromoteObservedRequests\(\)/);
  assert.match(backgroundSource, /harpoState\.pendingRequests\.set\(requestKey, observedRequest\)/);
  assert.match(backgroundSource, /case "Network\.dataReceived": \{/);
  assert.match(backgroundSource, /case "Network\.responseReceivedExtraInfo": \{/);
  assert.match(backgroundSource, /case "Fetch\.requestPaused": \{/);
  assert.match(backgroundSource, /Fetch\.getResponseBody/);
  assert.match(backgroundSource, /headers:\s*params\.headers,\s*status:\s*params\.statusCode/s);
  assert.match(backgroundSource, /const observedRequest = harpoState\.observedRequests\.get\(requestKey\)/);
  assert.match(backgroundSource, /pendingRequest\?\.url \|\| observedRequest\?\.url \|\| ""/);
  assert.match(backgroundSource, /const requestKey = harpoBuildRequestKey\(tabId, params\.requestId\)/);
  assert.match(backgroundSource, /harpoMaybeCaptureRequestPostData\(tabId, params\.requestId, requestKey, observedRequest, params\.request\)/);
  assert.match(backgroundSource, /if \(!pendingRequest && !harpoState\.observedRequests\.has\(requestKey\)\) break/);
  assert.match(backgroundSource, /harpoState\.completedObservedRequests\.set\(requestKey,/);
  assert.match(backgroundSource, /chrome\.tabs\.onCreated\.addListener\(harpoHandleTrackedTabCreated\)/);
  assert.match(backgroundSource, /chrome\.webNavigation\.onCreatedNavigationTarget\.addListener\(harpoHandleCreatedNavigationTarget\)/);
  assert.match(backgroundSource, /redirectURL:\s*redirectUrl,/);
  assert.match(backgroundSource, /harpoMergeResponseRecord\(\s*harpoState\.pendingResponses\.get\(requestKey\),\s*harpoNormalizeResponseRecord\(params\.response, params\.timestamp\)\s*\)/s);
  assert.match(backgroundSource, /if \(!captureDecision\.allowCapture\) \{/);
  assert.match(backgroundSource, /if \(captureDecision\.physicalAssetTraffic\) \{/);
  assert.match(backgroundSource, /if \(captureDecision\.logoutTraffic && !captureDecision\.nextSession\.externalTrafficWindowOpen\) \{/);
  assert.match(backgroundSource, /if \(captureDecision\.returnedToProgrammerDomain && captureDecision\.nextSession\.logoutDetected\) \{/);
  assert.match(backgroundSource, /harpoRequestAutoStop\(\)/);
  assert.match(backgroundSource, /harpoBuildHar\(captureSession = createHarpoCaptureSession\(\)\)/);
  assert.match(backgroundSource, /const entries = \[\.\.\.harpoState\.entries\]/);
  assert.match(backgroundSource, /await Promise\.allSettled\(\[\.\.\.harpoState\.pendingRequestPostData\.values\(\)\]\)/);
  assert.match(backgroundSource, /const fallbackComment = harpoBuildMissingBodyComment\(req, resp,/);
  assert.match(backgroundSource, /const responseBodyCandidate = bodyMap\.get\(requestKey\)/);
  assert.match(backgroundSource, /const responseBody = harpoHasBodyResult\(responseBodyCandidate\)/);
  assert.match(backgroundSource, /HARPO exhausted Fetch interception, streaming capture, and Network\.getResponseBody retries\./);
  assert.match(backgroundSource, /No response bytes were recorded for this response\./);
  assert.match(backgroundSource, /\.filter\(\(entry\) => harpoShouldPersistEntry\(entry, captureSession\)\)/);
  assert.match(backgroundSource, /safeDomains:\s*harpoState\.safeDomains/);
  assert.match(backgroundSource, /programmerDomains:\s*harpoState\.programmerDomains/);
  assert.match(backgroundSource, /mvpdDomains:\s*Array\.isArray\(harpoState\.captureSession\?\.mvpdDomains\)/);
  assert.match(backgroundSource, /Array\.isArray\(message\?\.safeDomains\)/);
  assert.match(backgroundSource, /Array\.isArray\(message\?\.programmerDomains\)/);
  assert.doesNotMatch(backgroundSource, /Response body unavailable/);
  assert.doesNotMatch(backgroundSource, /Timed out while fetching response body/);
  assert.doesNotMatch(harpoSource, /This HAR references a non-zero response body size/);
});
